//
// Created by cain on 21/10/2025.
//

#include <iostream>
#include <ostream>

#include "encryption/Enigma.h"

using namespace Encryption;

int main()
{

    // Rotors and reflectors initialized (see assignment)
    Rotor rotor0 = Rotor{"AJDKSIRUXBLHWTMCQGZNPYFVOE"};
    Rotor rotor1 = Rotor{"EKMFLGDQVZNTOWYHXUSPAIBRCJ"};
    Rotor rotor2 = Rotor{"BDFHJLCPRTXVZNYEIWGAKMUSQO"};
    Rotor rotor3 = Rotor{"THEQUICKBROWNFXJMPSVLAZYDG"};
    Rotor rotor4 = Rotor{"XANTIPESOKRWUDVBCFGHJLMQYZ"};

    rotor1.setStartPosition('A');
    rotor0.setStartPosition('A');
    rotor4.setStartPosition('A');

    Reflector reflector = Reflector{"YRUHQSLDPXNGOKMIEBFZCWVJAT"};

    PlugBoard plugBoard = PlugBoard({{'A', 'P'}, {'C', 'M'}, {'D', 'E'}, {'G', 'L'}, {'J', 'Z'}, {'T', 'W'}});

    // Crib
    std::string crib = "DEOPGAVEVOORENIGMA";


    Enigma enigma = Enigma(rotor1, rotor0, rotor4, reflector, plugBoard);

    char * c = enigma.encrypt("PGWDJTWRAQJFJDLTOQLWGZZSNFADTWMJFJHKVYYFIIYBGSJIMAOKAGNYEDPJMSGZHKHPDNWIMZYBQGZACDYQHHFGUYSWJRMSQWJEHPSGFCBNNMFLXFQXBXDYAJLVMZDXXLEGEAQWCSIWYTCPJSMABNYYRZQSXFHBSVXKUTFDTWJFOCRIJFIUSGNPXAWYCFHVNCOIIUAPLZPAQJQNIWDYCDTKVFMSUWQNUHYQRFAANOMZAQVNMXZHUAWDOXGQJRPXWPESXZEDPLPDUMSGEVRPDSCEXPQVSBSGRUSPXYOPCFQEUJTLXMHAQQDAWSMJDUITVMNOPDNIOVOKUHTGBONGIJQMVLQIGLSNMNBSTITNPZVILKERIMOPLPSFFFVYNWCQOGDZSDDNXHHSNNQQWPNJTWBILLWMZPSHMEOLBJUESINPVMCANWVREOFXWWASELJDCIHPDMVDKMUBRYWFQFPZIVYKMLUGRPUDFQWLPRIUOZXARHQPZVYEZNCNVSYQFCBNLFGQLDODQJSXJGSBWUVDBVIKLRSMYPKSFFNGSIXKXXGJUFZDZWZQYTDXBUSXJCSSWDKFATQCYXEAYBJNTUXKHSQLAPHDBXSMCDHBMXJYKRJDVAYRKYHPSGVCBNCGNSMSYIWIKTBSTUGFPOAUCJMMGNWAVCYTTWQNIBEDRBNUSWVMPYEBKZGNLQFEUEXZSUXXMAODXUMRFXLKPGDCXEEZJMKYSFGVWPGTOCNXYRXIWOTESFVOKTQTAXZEQSYWXZQXWWPHULBNMRKXKYKIQXITEBJWLXKYMHBOCDTAUFGVVDCDAMVHBMOWDDNULXBVLYCNLVYRKXRKMLEJVHHXWZAILKWGKVKGHIKIYOVOOCDHRMBJYJUAYZIYSGDOEYSELOCATJCIGYNMJJNCJVSXWDBPXHYZTVXLNFLWCIICKYXQLRPFZYLTWURMLKAWNBTURLIRCJDSFQXPDTKUMTGHDQAIASIDAQBRDLORGSCNVSODANCAMOCXIQHZXYZZDJESUVNOEIVRVKXHIUYMIXZBHJTJHQRLHAJRDTJRBCMUDRAIOJELARZMHMOOUAHOHYRKZIOTLYUZEORDLHLCGITZBCCOWKXMXIXTNILSXSVKNTXYHTYLDFNGMEMXLTUECZTWGLWBHTYCMSTEPHFJZTGWCERFUUOJCOVIQOFUIEZKTJHJZZXXGWKSJTITDCIBKMVPPNVPQNJLYUPQIHIOQFGNCTUODSDNGSYWGQKWETKLBKSLNZSXPLJIENOQCMCZJMYLHXSKMIKUYWHXKZAZYQJIIMNCHGERPZELIPWGLDSHRUNNJWETCLAHPCJFMRCULYMKAZDSXRWNSFNIWHGIYNFRVTGYGJJMUCOOKPOGLZNBDRBOTEPGUCPLVUVDVNOTXVKKDQVWJSDSDTLUMVZFLDQIMKYBDUGJUOAYSWXCLFLCFEOGQSRELMOSTCDELSXJYDJYOFRYZJLMKQLWTNVWBYIOTQVNLZRFPHORGQTQIOJQJJZUDEXXSUKDIXLOQEAAXSOJCVPZSHPRMRINOXYLJDQZJIBWJZSPUATHPRYFUNWZDOUQGWDIHDFODSFDWQFSWLPYRVMESBLWCFJINYRUXNMPPKITMRFFDQZVLIIZKWTFYHTYWXTQOUWKVIIIUCRFJILPSZDRXSUJJGIWQHYZNYWKDGRFFDARFGPZCBHTYTGQEVGMSUNMGXZPBVITOTHQRENVJNAVAMNKPMPJFMAUCAXYMYIESSVLXOEVACZHFHZDMOFVMKRJJFJWXSWMMYYZXCKHFFBEPVDZDKRIUFHUYEVMDWCXQVFAQXBABVGHNOTSKNIWCDMWCBRRKGPWKDPLZPQRXWJGWWGTZMZEDGWALHWJVBATCBKDARLWXMMWAXSPEVCGVBOXYZAZBFNSQHUDNAZDXVGFEKRQNWSDDZBNNTOMIM");
    std::cout << c << std::endl;

}
